config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  has_one_attached :upload

  validate :upload_content_type

  private

  def upload_content_type
    if upload.attached? && !upload.content_type.in?(%w(image/jpeg image/png application/pdf))
      errors.add(:upload, 'must be a JPEG, PNG, or PDF')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :description, :completed, :notes, :upload)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recruitment2024</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="card m-8 p-8">
<%= form_with(model: task, html:{class: "form-horizontal"}) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row m-2 p-2">
      <div class="col text-center fs-5">
        <%= form.label :name %>
      </div>
      <div class="col">
        <%= form.text_field :name, class: "form-control" %>
      </div>
  </div>
  <div class="row m-2 p-2">
      <div class="col text-center fs-5">
        <%= form.label :description %>
      </div>
      <div class="col">
        <%= form.text_field :description, class: "form-control" %>
      </div>
  </div>
  <div class="row m-2 p-2">
      <div class="col text-center fs-5">
        <%= form.label :completed %>
      </div>
      <div class="col">
        <%= form.check_box :completed %>
      </div>
  </div>
  <div class="row m-2 p-2">
      <div class="col text-center fs-5">
        <%= form.label :notes %>
      </div>
      <div class="col">
        <%= form.text_field :notes, class: "form-control" %>
      </div>
  </div>
  <div class="row m-2 p-2">
      <div class="col text-center fs-5">
        <%= form.label :upload %>
      </div>
      <div class="col">
        <%= form.file_field :upload, class: "form-control" %>
      </div>
  </div>

  <div class="actions row">
    <div class="col text-center fs-5">
      <%= form.submit "Create Task", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>
<div class="d-flex align-items-center justify-content-center">
    <%= link_to 'Show', @task, class: "btn btn-success text-white" %> | 
    <%= link_to 'Back', tasks_path, class: "btn btn-dark text-white" %>
</div>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>
<style>
  th, td {
    text-align: center;
    margin: auto;
  }
</style>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Completed</th>
      <th>Notes</th>
      <th>Upload</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.completed %></td>
        <td><%= task.notes %></td>
        <td><%= image_tag task.upload, style: 'width: 500px' %></td>
        <td><%= link_to 'Show', task, class:"btn btn-primary text-white" %></td>
        <td><%= link_to 'Edit', edit_task_path(task), class: "btn btn-success text-white" %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger text-white" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="d-flex align-items-center justify-content-center">
  <%= link_to 'New Task', new_task_path, class: "btn btn-primary text-white" %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>
<div class="d-flex align-items-center justify-content-center">
  <%= link_to 'Back', tasks_path, class: "btn btn-dark text-white" %>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card mb-8">
  <div class="m-auto">
  <div class="row text-center">
    <div class="col fs-4">
      <strong>Name:</strong>
    </div>
    <div class="col fs-6">
      <%= @task.name %>
    </div>
  </div>
  <div class="row text-center">
    <div class="col fs-4">
      <strong>Description:</strong>
    </div>
    <div class="col fs-6">
      <%= @task.description %>
    </div>
  </div>
  <div class="row text-center">
    <div class="col fs-4">
      <strong>Completed:</strong>
    </div>
    <div class="col fs-6">
      <%= @task.completed %>
    </div>
  </div>
  <div class="row text-center">
    <div class="col fs-4">
      <strong>Notes:</strong>
    </div>
    <div class="col fs-6">
      <%= @task.notes %>
    </div>
  </div>
  <div class="row text-center">
    <div class="col fs-4">
      <strong>Upload:</strong>
    </div>
    <div class="col fs-6">
      <%= image_tag @task.upload, style: 'width: 500px' %>
    </div>
  </div>
  </div>
</div>
<br>
<div class="d-flex align-items-center justify-content-center">
    <%= link_to 'Edit', edit_task_path(@task), class: "btn btn-success text-white" %> | 
    <%= link_to 'Back', tasks_path, class: "btn btn-dark text-white" %>
</div>